modLoader="javafml"
loaderVersion="[33,)"
authors="davidmaamoaix"
license="All rights reserved"

[[mods]]
modId="tinymobfarm"
version="1.1.0"
displayName="Tiny Mob Farm"
description='A Minecraft Mod that adds single block mob farms that generates mob drops passively.'